name: Deploy Hexo Blog

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            export PATH="$HOME/.bun/bin:$PATH"
            
            cd /root/code/blog
            git pull
            npm run build
            sudo rsync -av --delete /root/code/blog/public/ /opt/1panel/www/sites/blog.quhou.top/index/
            sudo chown -R 1000:1000 /opt/1panel/www/sites/blog.quhou.top/index/
